events {}

http {

    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    upstream frontend {
        server frontend:3000;
    }

    upstream backend {
        server eco_backend:8000;
    }

    server {

        listen 80;
        server_name _;

        client_max_body_size 50M;

        # =========================
        # STATIC
        # =========================
        location ^~ /static/ {
            alias /app/staticfiles/;
            try_files $uri =404;
        }

        # =========================
        # MEDIA 추가 (핵심)
        # =========================
        location ^~ /media/ {
            alias /app/media/;
            try_files $uri =404;
        }

        # =========================
        # Django Admin
        # =========================
        location /admin/ {

            proxy_pass http://backend;

            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # =========================
        # API
        # =========================
        location /api/ {

            proxy_pass http://backend;

            proxy_http_version 1.1;

            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

            proxy_set_header Authorization $http_authorization;
        }

        # =========================
        # Frontend
        # =========================
        location / {

            proxy_pass http://frontend;

            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-Proto $scheme;

            proxy_http_version 1.1;

            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }
    }
}